# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` 

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.26.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl.exe"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl.exe"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2023.1",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/ALVI COMPUTER/.conda/envs/traning_env/Library/include",
      "lib directory": "C:/Users/ALVI COMPUTER/.conda/envs/traning_env/Libr

C:\Users\ALVI COMPUTER\.conda\envs\traning_env\lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10

In [3]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array 

In [6]:
print(np.size(arr))
print(arr.itemsize)
np.size(arr)*arr.itemsize

10
8


80

#### 5. How to get the documentation of the numpy add function from the command line?

In [7]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [8]:
arr=np.zeros(10,dtype=int)
arr[4]=1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49

In [9]:
arr=np.arange(10,49+1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last)

In [10]:
arr=np.flip(arr)
arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
arr=np.arange(0,8+1).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [13]:
lst=np.array([1,2,0,0,4,0])
ind=np.where(lst!=0)

In [14]:
ind

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [15]:
iden_mat=np.eye(3,3)
iden_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [18]:
arr=np.random.rand(3,3,3)
arr

array([[[0.23139317, 0.12074295, 0.43115208],
        [0.20674057, 0.26291596, 0.00182412],
        [0.13803859, 0.35197147, 0.75558063]],

       [[0.97372045, 0.49598521, 0.96153432],
        [0.2962114 , 0.62843169, 0.03278443],
        [0.31115518, 0.40628797, 0.64973101]],

       [[0.46137131, 0.66408128, 0.31377348],
        [0.93305278, 0.34809166, 0.15873913],
        [0.58502116, 0.52453076, 0.3994056 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [19]:
arr=np.random.rand(10,10)
arr

array([[0.07644253, 0.7244191 , 0.73696897, 0.98767464, 0.06631675,
        0.099331  , 0.54739783, 0.91051508, 0.08683113, 0.13835956],
       [0.35271139, 0.54711664, 0.74524013, 0.50198572, 0.25324209,
        0.4763358 , 0.25775917, 0.42133902, 0.26342653, 0.4278187 ],
       [0.66127135, 0.61167359, 0.89229904, 0.38586222, 0.04845922,
        0.28265341, 0.34750809, 0.05851799, 0.92321363, 0.77393884],
       [0.88230729, 0.65783872, 0.52530736, 0.51792081, 0.32587062,
        0.69967339, 0.91875314, 0.80678946, 0.47550109, 0.95291434],
       [0.08990227, 0.64649025, 0.07271714, 0.0860031 , 0.24469   ,
        0.28016432, 0.46321619, 0.27304641, 0.94679658, 0.41092031],
       [0.54472952, 0.8745986 , 0.40349701, 0.35262428, 0.95717389,
        0.75015367, 0.80276494, 0.60930322, 0.74205702, 0.53408911],
       [0.3107607 , 0.94435681, 0.08076165, 0.33469182, 0.10577461,
        0.39283274, 0.0851874 , 0.32268807, 0.20874567, 0.19338828],
       [0.12599715, 0.0137376 , 0.0522909

In [20]:
print(np.max(arr))
print(np.min(arr))

0.9876746383276479
0.013737598313588562


#### 14. Create a random vector of size 30 and find the mean value

In [21]:
arr=np.random.random(30)
print(arr)
np.mean(arr)

[4.02033399e-01 1.11071054e-01 4.06197365e-01 7.99108981e-01
 1.84647248e-01 3.17014114e-01 1.16898872e-01 2.83875971e-01
 1.47655096e-01 2.55469764e-01 1.51439045e-01 2.33424656e-01
 8.07912490e-02 2.28749878e-01 8.30768655e-01 7.16537563e-02
 2.68854657e-01 2.83415677e-04 7.28016519e-01 4.27085813e-01
 8.87412275e-01 1.95657898e-01 6.41360145e-01 9.14372775e-01
 6.59818635e-01 9.02045817e-01 4.17649444e-01 1.04227220e-01
 2.86809294e-01 9.68785413e-01]


0.40077261409316284

#### 15. Create a 2d array with 1 on the border and 0 inside

In [3]:
arr=np.ones((10,10))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

#### 16. How to add a border (filled with 0's) around an existing array?

In [4]:
arr=np.pad(arr,pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [31]:
arr=np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [30]:
arr=np.zeros((8,8),dtype=int)
arr[1::2,::2]=1
arr[::2,1::2]=1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [32]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function

In [33]:
arr=np.tile( np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix

In [34]:
arr=np.random.random((5,5))
print(arr)
arr_max,arr_min=np.max(arr),np.min(arr)
print(arr_max,arr_min)
arr=(arr-arr_min)/(arr_max-arr_min)
arr

[[0.96954097 0.49864198 0.03980689 0.53479407 0.22941131]
 [0.0070378  0.51839502 0.71434935 0.79226271 0.3710277 ]
 [0.55197597 0.26179891 0.64673419 0.42427358 0.70944176]
 [0.13377933 0.40838378 0.80908697 0.0555559  0.37121854]
 [0.37602386 0.28767802 0.50085716 0.78603363 0.58374219]]
0.9695409693715353 0.007037802146137473


array([[1.        , 0.51075591, 0.0340457 , 0.54831639, 0.23103665],
       [0.        , 0.53127848, 0.73486673, 0.8158154 , 0.37817008],
       [0.56616766, 0.26468599, 0.66461743, 0.43349029, 0.72976794],
       [0.13167908, 0.41698147, 0.83329509, 0.05040825, 0.37836835],
       [0.38336087, 0.29157329, 0.51305739, 0.80934365, 0.59917142]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [43]:
d_type=np.dtype([
    ("r", np.ubyte, 1),
    ("g", np.ubyte, 1),
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1)
])
d_type

C:\Users\ALVI COMPUTER\AppData\Local\Temp\ipykernel_5628\1861224017.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  d_type=np.dtype([


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [35]:
mt1=np.ones((5,3))
mt2=np.ones((3,2))
mt3=np.dot(mt1,mt2)
mt3

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [38]:
arr=np.arange(10)
arr[(arr>3) & (arr<8)]*=-1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [15]:
# all these are legal
z=10
print(z**z)
2 << z >> 2
z <- z
1j*z
z/1/1

10000000000


10.0

In [40]:
z<z>  //illegal

SyntaxError: invalid syntax (656927738.py, line 1)

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [21]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\ALVI COMPUTER\AppData\Local\Temp\ipykernel_9848\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\ALVI COMPUTER\AppData\Local\Temp\ipykernel_9848\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\ALVI COMPUTER\AppData\Local\Temp\ipykernel_9848\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ?

In [43]:
arr = np.random.uniform(-10,+10,10)
print(arr)
print(np.copysign(np.ceil(np.abs(arr)),arr))

[-4.99433141  9.6661387  -3.39573355  7.36516506  6.16453142  7.79077858
 -6.61894472  7.35495754  7.81486646 -3.60402604]
[-5. 10. -4.  8.  7.  8. -7.  8.  8. -4.]


#### 30. How to find common values between two arrays?

In [44]:
arr1=np.arange(10)
arr2=np.arange(7,15)
arr3=np.intersect1d(arr1,arr2)
arr3

array([7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)?

In [45]:
defaults = np.seterr(all="ignore")
Z = np.ones(1)/0
_ = np.seterr(**defaults)
print(Z)

[inf]


#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [46]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\ALVI COMPUTER\AppData\Local\Temp\ipykernel_9600\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [47]:
yest=np.datetime64('today','D')-np.timedelta64(1,'D')
tod=np.datetime64('today','D')
tomor=np.datetime64('today','D')+np.timedelta64(1,'D')
print(yest)
print(tod)
print(tomor)

2024-07-05
2024-07-06
2024-07-07


#### 34. How to get all the dates corresponding to the month of July 2016?

In [48]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [78]:
a=np.ones(3)*1
b=np.ones(3)*2
np.add(a,b,out=b)

array([3., 3., 3.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [4]:
arr=np.random.uniform(0,10,10)
print(arr-arr%1)
print(np.floor(arr))
print(np.ceil(arr))
print(np.trunc(arr))

[6. 5. 3. 7. 6. 4. 3. 8. 0. 0.]
[6. 5. 3. 7. 6. 4. 3. 8. 0. 0.]
[7. 6. 4. 8. 7. 5. 4. 9. 1. 1.]
[6. 5. 3. 7. 6. 4. 3. 8. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [10]:
arr=np.zeros((5,5))
arr+=range(0,5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [12]:
def generator():
    for  x in range(10):
        yield x

arr=np.fromiter(generator(),dtype=float,count=-1)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [18]:
arr=np.linspace(0,1,12,endpoint=True)[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it

In [23]:
arr=np.random.random(10)
arr.sort()
arr

array([0.00774987, 0.0439505 , 0.22706713, 0.50163396, 0.51738909,
       0.7574712 , 0.80041994, 0.88532606, 0.88693969, 0.96882941])

#### 41. How to sum a small array faster than np.sum?

In [24]:
arr=np.arange(10)
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal

In [30]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
equal=np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

[1 0 1 1 0] [0 1 1 0 1]
False
False


#### 43. Make an array immutable (read-only) 

In [32]:
arr=np.zeros(10)
arr.flags.writeable=False
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [8]:
arr=np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.02967628 0.86334675 1.25345271 0.75070548 0.51592517 0.61232762
 0.96794031 1.01456498 0.71116582 1.05057168]
[0.66640396 0.84037377 0.87606799 0.44325277 0.68736088 1.29064928
 0.36423756 0.47266956 0.0946835  0.86523061]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [14]:
arr=np.random.random(10)
index=np.argmax(arr)
print(index)
print(arr)
arr[index]=0
arr

8
[0.34963238 0.06155661 0.41470462 0.62400068 0.10222373 0.55966533
 0.15813396 0.17614639 0.97000463 0.20509144]


array([0.34963238, 0.06155661, 0.41470462, 0.62400068, 0.10222373,
       0.55966533, 0.15813396, 0.17614639, 0.        , 0.20509144])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [16]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [21]:
x=np.arange(8)
y=x+.5
c=1.0/np.subtract.outer(x,y)
np.linalg.det(c)

3638.1636371179666

#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [22]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? 

In [26]:
arr=np.zeros((16,16))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [31]:
z = np.arange(100)
v = np.random.uniform(0,100)
print(z,v)
index = (np.abs(z-v)).argmin()
print(z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 67.8618774631623
68


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [33]:
arr= np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\ALVI COMPUTER\AppData\Local\Temp\ipykernel_1092\4131357797.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr= np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [34]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.79032644 0.60928253 0.60556854 0.20638634 0.7655442
  0.32151639 0.60150511 0.18210378 0.7379137 ]
 [0.79032644 0.         0.71951414 0.84587731 0.87816321 0.53867551
  0.46987437 0.65509953 0.90202108 0.82823072]
 [0.60928253 0.71951414 0.         0.13778211 0.81273562 0.28168126
  0.50906913 0.06504754 0.54963885 0.14277262]
 [0.60556854 0.84587731 0.13778211 0.         0.81187593 0.4162121
  0.57855781 0.20066514 0.50668877 0.1600751 ]
 [0.20638634 0.87816321 0.81273562 0.81187593 0.         0.94851122
  0.4427878  0.80091001 0.35026478 0.94344855]
 [0.7655442  0.53867551 0.28168126 0.4162121  0.94851122 0.
  0.54375289 0.22999839 0.76283643 0.3272267 ]
 [0.32151639 0.46987437 0.50906913 0.57855781 0.4427878  0.54375289
  0.         0.46827462 0.44005453 0.65165161]
 [0.60150511 0.65509953 0.06504754 0.20066514 0.80091001 0.22999839
  0.46827462 0.         0.5614947  0.19014182]
 [0.18210378 0.90202108 0.54963885 0.50668877 0.35026478 0.76283643
  0.44005453 0.5614947

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [36]:
arr = np.arange(10, dtype=np.int32)
arr = arr.astype(np.float32, copy=False)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [42]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.str_)
print(Z)

[['1' ' 2' ' 3' ' 4' ' 5']
 ['6' '  ' '  ' ' 7' ' 8']
 ['' '  ' ' 9' '10' '11']]


#### 55. What is the equivalent of enumerate for numpy arrays?

#### 56. Generate a generic 2D Gaussian-like array

#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

#### 63. Create an array class that has a name attribute

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product?

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

#### 72. How to swap two rows of an array?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).